package edu.uw.tcss450.team8tcss450.ui.chat.conversation;

import android.app.Application;

import com.android.volley.DefaultRetryPolicy;
import com.android.volley.Request;
import com.android.volley.VolleyError;
import com.android.volley.toolbox.JsonObjectRequest;
import com.android.volley.toolbox.Volley;

import org.json.JSONObject;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.function.IntFunction;

import androidx.annotation.NonNull;
import androidx.lifecycle.AndroidViewModel;
import androidx.lifecycle.LifecycleOwner;
import androidx.lifecycle.MutableLiveData;
import androidx.lifecycle.Observer;

/**
 * Modified from Charles Bryan's lab assignment for the course TCSS 450.
 *
 * View Model Class to support the Chat Message Fragment class. Handles server access features and
 * GET/POST functions.
 * TODO update to live server, include catches for live updates from services
 *
 * @author Charles Bryan
 * @version
 * @author Marc Perez
 * @version 6 May 2021
 */
public class MessageListViewModel extends AndroidViewModel {
    /**
     * Temporary string filler. Generated using BaconIpsum.com
     *  TODO DELETE LATER
     */
    private final String mTempMessage = "Bacon ipsum dolor amet short ribs meatloaf chuck chislic capicola. ";
    /**
     * List of Messages held by the recycler view.
     */
    private MutableLiveData<List<Message>> mMessageList;

    /**
     * public constructor.
     * @param application Application data object.
     */
    public MessageListViewModel(@NonNull Application application) {
        super(application);
        mMessageList = new MutableLiveData<>();
        mMessageList.setValue(new ArrayList<>());
    }

    /**
     * TODO fill in this javadoc
     * @param owner
     * @param observer
     */
    public void addChatListObserver(@NonNull LifecycleOwner owner,
                                    @NonNull Observer<? super List<Message>> observer) {
        mMessageList.observe(owner, observer);
    }

    /**
     * Volley function to receive and handle error responses from the server.
     * TODO Currently bypasses errors, update when live data is valid.
     * @param error Error object generated by Volley.
     */
    private void handleError(final VolleyError error) {
        //Log.e("CONNECTION ERROR", error.getLocalizedMessage());
        //throw new IllegalStateException(error.getMessage());      // TODO fix when server is set up
        handleResult(null);
    }

    /**
     * Received and interprets data sent from Volley.
     * TODO Currently generates dummy data, update when live data is valid.
     * @param result A JSONObject generated by Volley with valid data.
     */
    private void handleResult(final JSONObject result) {
        mMessageList.setValue(new ArrayList<>());
        for(int i = 0; i < 10; i++) {    // TODO remove when live data is implemented
            Message post = new Message(
                    "My Dearest Friend #?", mTempMessage + (i + 1));
            if (!mMessageList.getValue().contains(post)) {
                mMessageList.getValue().add(post);
            }
        }
        mMessageList.setValue(mMessageList.getValue());
    }

    /**
     * Sends a GET to the server requesting message data.
     * TODO add contactID to request, update link to a valid URL.
     * @param jwt a verified jwt object.
     */
    public void connectGet(String jwt) {
        String url =
                "https://team8-tcss450-app.herokuapp.com/auth";    // TODO change to live data source
        Request request = new JsonObjectRequest(
                Request.Method.GET,
                url,
                null, //no body for this get request
                this::handleResult,
                this::handleError) {
            @Override
            public Map<String, String> getHeaders() {
                Map<String, String> headers = new HashMap<>();
                // add headers <key,value>
                headers.put("Authorization", jwt);
                return headers;
            }
        };
        request.setRetryPolicy(new DefaultRetryPolicy(
                10_000,
                DefaultRetryPolicy.DEFAULT_MAX_RETRIES,
                DefaultRetryPolicy.DEFAULT_BACKOFF_MULT));
        //Instantiate the RequestQueue and add the request to the queue
        Volley.newRequestQueue(getApplication().getApplicationContext())
                .add(request);
    }
}
